# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 05:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
